export type GlossaryTerm = {
  id: string;
  term: string;
  english?: string;
  definition: string;
  category: "AI技术" | "检索与评测" | "产品方法论" | "工具平台";
};

/** 面试题库高频 AI / PM 术语（本地速查，可后续迁 Notion） */
export const QUESTION_BANK_GLOSSARY: GlossaryTerm[] = [
  {
    id: "rag",
    term: "RAG",
    english: "Retrieval-Augmented Generation",
    category: "AI技术",
    definition: "先检索相关文档，再让大模型基于检索结果生成回答。核心是「用外部知识补模型短板」，不是纯靠参数记忆。",
  },
  {
    id: "agent",
    term: "Agent",
    english: "智能体",
    category: "AI技术",
    definition: "能感知目标、规划步骤、调用工具并迭代执行的 AI 系统。比单次问答更强调「闭环行动」。",
  },
  {
    id: "multi-agent",
    term: "Multi-Agent",
    english: "多智能体",
    category: "AI技术",
    definition: "多个 Agent 分工协作（规划、执行、审查等）。价值在角色拆分与协作协议，难点在通信成本和一致性。",
  },
  {
    id: "embedding",
    term: "Embedding",
    english: "向量化",
    category: "检索与评测",
    definition: "把文本转成高维向量，用相似度检索语义相近内容。RAG 里常见的「语义检索」底座。",
  },
  {
    id: "rerank",
    term: "Rerank",
    english: "重排序",
    category: "检索与评测",
    definition: "先粗召回一批候选，再用更精的模型重排。常见路径：向量召回 + Cross-encoder 精排。",
  },
  {
    id: "lora",
    term: "LoRA",
    english: "Low-Rank Adaptation",
    category: "AI技术",
    definition: "用低秩矩阵做参数高效微调。适合小数据、低成本把通用模型适配到垂直场景。",
  },
  {
    id: "prompt-engineering",
    term: "Prompt 工程",
    english: "Prompt Engineering",
    category: "AI技术",
    definition: "通过指令、示例、约束把模型行为调到可用。产品侧常和评测、模板版本管理一起做。",
  },
  {
    id: "vibe-coding",
    term: "vibe coding",
    english: "AI 辅助编程",
    category: "工具平台",
    definition: "用自然语言驱动 AI 写代码、改代码。PM 面试里常用来证明「能落地原型 / 自己验证想法」。",
  },
  {
    id: "harness",
    term: "Harness 工程",
    english: "Harness Engineering",
    category: "AI技术",
    definition: "围绕模型之外的运行框架：工具、记忆、循环、评测与产品化封装。重点是让模型能力稳定变成产品能力。",
  },
  {
    id: "mcp",
    term: "MCP",
    english: "Model Context Protocol",
    category: "工具平台",
    definition: "给模型接入外部工具/数据源的协议层。目标是标准化「模型如何安全、可扩展地连上上下文」。",
  },
  {
    id: "react",
    term: "ReAct",
    english: "Reasoning + Acting",
    category: "AI技术",
    definition: "交替做「思考」和「行动（调工具）」的范式。很多 Agent 循环的基础套路。",
  },
  {
    id: "coze",
    term: "Coze / 扣子",
    english: "ByteDance Agent 平台",
    category: "工具平台",
    definition: "面向搭建 Bot / Agent 的低代码平台。面试里常对比 Dify、自研 Agent 框架的取舍。",
  },
  {
    id: "dify",
    term: "Dify",
    english: "LLM App 开发平台",
    category: "工具平台",
    definition: "开源的 LLM 应用开发平台，覆盖工作流、RAG、Agent。适合快速验证产品形态。",
  },
  {
    id: "langgraph",
    term: "LangGraph",
    english: "LangChain 图编排",
    category: "工具平台",
    definition: "用图结构编排多步骤 Agent 流程。适合需要状态管理、分支与循环的复杂工作流。",
  },
  {
    id: "prd",
    term: "PRD",
    english: "Product Requirements Document",
    category: "产品方法论",
    definition: "产品需求文档：问题、目标用户、方案、边界与验收标准。AI 产品 PRD 还要写清模型边界与失败兜底。",
  },
  {
    id: "mvp",
    term: "MVP",
    english: "Minimum Viable Product",
    category: "产品方法论",
    definition: "最小可行产品：用最小成本验证核心假设。AI MVP 常先验证「价值是否成立」，再谈模型极致效果。",
  },
  {
    id: "north-star",
    term: "北极星指标",
    english: "North Star Metric",
    category: "产品方法论",
    definition: "最能代表产品长期价值的单一核心指标。AI 产品要警惕「模型分」替代「业务结果」。",
  },
  {
    id: "ab-test",
    term: "A/B 测试",
    english: "A/B Testing",
    category: "产品方法论",
    definition: "对照实验比较方案效果。AI 场景常叠加线上/离线评测，避免只看主观好感。",
  },
  {
    id: "bad-case",
    term: "Bad case",
    english: "失败样例",
    category: "检索与评测",
    definition: "系统出错或体验差的真实案例。AI 产品迭代高度依赖 bad case 回流与分类治理。",
  },
  {
    id: "cross-encoder",
    term: "Cross-encoder",
    english: "交叉编码器",
    category: "检索与评测",
    definition: "把 query 和文档一起编码打分，精排更准但更贵。常用于 Rerank。",
  },
  {
    id: "bi-encoder",
    term: "Bi-encoder",
    english: "双塔编码器",
    category: "检索与评测",
    definition: "query 与文档分别编码再算相似度，适合大规模召回。通常先 Bi-encoder，再 Cross-encoder。",
  },
  {
    id: "text-to-sql",
    term: "Text-to-SQL",
    english: "自然语言转 SQL",
    category: "AI技术",
    definition: "把自然语言问题转成 SQL。产品难点常在 schema 理解、权限与错误兜底，不只是生成句子。",
  },
  {
    id: "roi",
    term: "ROI",
    english: "Return on Investment",
    category: "产品方法论",
    definition: "投入产出比。AI 项目面试常问：算力/标注/人效成本 vs 业务收益如何量化。",
  },
  {
    id: "llm-as-judge",
    term: "LLM-as-Judge",
    english: "用大模型当评委",
    category: "检索与评测",
    definition: "用 LLM 给回答打分或比较优劣。便宜可扩展，但要校准偏差，最好搭配人工抽检。",
  },
  {
    id: "rrf",
    term: "RRF",
    english: "Reciprocal Rank Fusion",
    category: "检索与评测",
    definition: "把多路检索结果按排名融合。常用于「关键词 + 向量」混合召回。",
  },
  {
    id: "aigc",
    term: "AIGC",
    english: "AI Generated Content",
    category: "AI技术",
    definition: "AI 生成内容（文/图/视频等）。产品侧关注可控性、版权、质量评测与人机协同。",
  },
  {
    id: "chunking",
    term: "chunking / 切片",
    english: "文档分块",
    category: "检索与评测",
    definition: "把长文档切成可检索片段。切太大噪声高，切太碎丢上下文，直接影响 RAG 质量。",
  },
  {
    id: "top-k",
    term: "Top-K",
    english: "取前 K 条",
    category: "检索与评测",
    definition: "检索或生成时只保留前 K 个结果。K 越大召回更全，噪声和成本也更高。",
  },
  {
    id: "comfyui",
    term: "ComfyUI",
    english: "节点式图像工作流",
    category: "工具平台",
    definition: "可视化节点编排的图像生成工作流工具。常用于可控生成与工作流产品化讨论。",
  },
  {
    id: "kling",
    term: "Kling / 可灵",
    english: "快手视频生成模型",
    category: "工具平台",
    definition: "视频生成产品/模型方向的代表之一。面试里常用来聊 AIGC 视频的场景与评测。",
  },
  {
    id: "jimeng",
    term: "即梦 / 万象",
    english: "字节图像/视频生成",
    category: "工具平台",
    definition: "字节系 AIGC 创作工具。常与 Midjourney、可灵等对比产品定位与工作流。",
  },
  {
    id: "hyde",
    term: "HyDE",
    english: "Hypothetical Document Embedding",
    category: "检索与评测",
    definition: "先让模型生成「假想答案文档」，再拿它去做向量检索，改善短 query 的召回。",
  },
];

export const GLOSSARY_CATEGORIES = ["全部", "AI技术", "检索与评测", "产品方法论", "工具平台"] as const;
